"""create_bgm_table

Revision ID: aa73b9afdd3f
Revises: 
Create Date: 2026-06-16 10:19:06.902884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa73b9afdd3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bgms', sa.Column('artist', sa.String(), nullable=True))
    op.add_column('bgms', sa.Column('youtube_url', sa.String(), nullable=False))
    op.add_column('bgms', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_bgms_title'), 'bgms', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bgms_title'), table_name='bgms')
    op.drop_column('bgms', 'created_at')
    op.drop_column('bgms', 'youtube_url')
    op.drop_column('bgms', 'artist')
    # ### end Alembic commands ###
