"""add_bgm_logs_table

Revision ID: f48dc99747b5
Revises: b906cae451bf
Create Date: 2026-06-26 09:48:00.619134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f48dc99747b5'
down_revision: Union[str, None] = 'b906cae451bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bgm_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bgm_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bgm_logs_id'), 'bgm_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bgm_logs_id'), table_name='bgm_logs')
    op.drop_table('bgm_logs')
    # ### end Alembic commands ###
